[package]
name = "rsyscall-native"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[lib]
name = "rsyscall"
crate-type = ["cdylib"]
test = false
doctest = false
bench = false

[[bin]]
name = "rsyscall-bootstrap"
path = "src/bin/bootstrap.rs"
test = false
bench = false

[[bin]]
name = "rsyscall-stdin-bootstrap"
path = "src/bin/stdin_bootstrap.rs"
test = false
bench = false

[[bin]]
name = "rsyscall-unix-stub"
path = "src/bin/unix_stub.rs"
test = false
bench = false

[dependencies]
rsyscall-core = { path = "../core" }
