#!/usr/bin/env python3
"""Check a candidate <rsyscall.h> against the ABI of docs/spec/abi-layouts.generated.md.

The check compiles, with ``cc -fsyntax-only``, the exact C preamble that python/ffibuilder.py hands
to cffi (system headers plus the preamble's own struct definitions, then ``#include <rsyscall.h>``),
followed by ``_Static_assert`` checks of every struct size and field offset in the generated layout
tables and by type checks of the five symbol prototypes (native-abi.md §2, §3). A header that
redefines a preamble struct, mislays a field or declares a symbol with another type fails here,
before ``make venv`` does.

usage: header-check.py [--include-dir DIR] [--dump]
       DIR defaults to native/rsyscall/include; --dump prints the generated C instead of compiling.
"""
from __future__ import annotations
import argparse
import ast
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
LAYOUTS = ROOT / "docs" / "spec" / "abi-layouts.generated.md"
FFIBUILDER = ROOT / "python" / "ffibuilder.py"
STRUCTS = ["rsyscall_trampoline_stack", "rsyscall_syscall", "rsyscall_symbol_table",
           "rsyscall_bootstrap", "rsyscall_stdin_bootstrap", "rsyscall_unix_stub"]
PROTOTYPES = [  # native-abi.md §3 / python/ffibuilder.py L137, L1235-1239
    ("rsyscall_raw_syscall", "long (*{})(long, long, long, long, long, long, long)"),
    ("rsyscall_server", "int (*{})(int, int)"),
    ("rsyscall_persistent_server", "int (*{})(int, int, int)"),
    ("rsyscall_futex_helper", "void (*{})(void *)"),
    ("rsyscall_trampoline", "void (*{})(void)"),
]

def preamble() -> str:
    "The C source string passed to set_source_pkgconfig in python/ffibuilder.py"
    for node in ast.walk(ast.parse(FFIBUILDER.read_text())):
        if isinstance(node, ast.Call):
            if getattr(node.func, "id", None) == "_set_source":          # _set_source(ffibuilder, preamble)
                return node.args[1].value
            if getattr(node.func, "attr", None) == "set_source_pkgconfig":  # the upstream form
                return node.args[2].value
    sys.exit("header-check: no _set_source/set_source_pkgconfig call found in python/ffibuilder.py")

def layouts() -> dict[str, tuple[int, list[tuple[str, int]]]]:
    "struct name -> (sizeof, [(field, offset), ...]) from the generated layout tables"
    found: dict[str, tuple[int | None, list[tuple[str, int]]]] = {}
    current = None
    for line in LAYOUTS.read_text().splitlines():
        m = re.match(r"^### `struct (\w+)`", line)
        if m:
            current = m.group(1)
            found[current] = (None, [])
            continue
        if current is None:
            continue
        m = re.search(r"sizeof = (\d+)", line)
        if m and found[current][0] is None:
            found[current] = (int(m.group(1)), found[current][1])
            continue
        m = re.match(r"^\| `(\w+)` \| `[^`]*` \| (\d+) \| (\d+) \|", line)
        if m:
            found[current][1].append((m.group(1), int(m.group(2))))
    missing = [s for s in STRUCTS if s not in found or found[s][0] is None]
    if missing:
        sys.exit(f"header-check: layouts not found for {missing} in {LAYOUTS}")
    return {s: (found[s][0], found[s][1]) for s in STRUCTS}  # type: ignore[misc]

# cffi's generated C source includes <Python.h> first; pyconfig.h defines these feature-test
# macros, which the preamble's system headers rely on (e.g. ino64_t/off64_t for linux_dirent64).
FEATURE_MACROS = "#define _GNU_SOURCE 1\n#define _LARGEFILE64_SOURCE 1\n#define _FILE_OFFSET_BITS 64\n"

def generate() -> str:
    out = [FEATURE_MACROS + preamble(), "", "#include <stddef.h>",
           "/* Checks generated by scripts/header-check.py from docs/spec/abi-layouts.generated.md */"]
    for name, (size, fields) in layouts().items():
        out.append(f'_Static_assert(sizeof(struct {name}) == {size}, "sizeof(struct {name}) != {size}");')
        for field, offset in fields:
            out.append(f'_Static_assert(offsetof(struct {name}, {field}) == {offset}, '
                       f'"offsetof({name}, {field}) != {offset}");')
    for sym, ptr in PROTOTYPES:
        out.append(f"static {ptr.format('const check_' + sym)} __attribute__((unused)) = {sym};")
    return "\n".join(out) + "\n"

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--include-dir", default=str(ROOT / "native" / "rsyscall" / "include"))
    ap.add_argument("--dump", action="store_true")
    args = ap.parse_args()
    source = generate()
    if args.dump:
        sys.stdout.write(source)
        return 0
    header = pathlib.Path(args.include_dir) / "rsyscall.h"
    if not header.is_file():
        print(f"header-check: {header} not found", file=sys.stderr)
        return 2
    with tempfile.TemporaryDirectory() as tmp:
        c = pathlib.Path(tmp) / "header-check.c"
        c.write_text(source)
        proc = subprocess.run(["cc", "-fsyntax-only", "-Wall", f"-I{args.include_dir}", str(c)],
                              capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        print(f"header-check: {header} FAILED", file=sys.stderr)
        return 1
    if proc.stderr.strip():
        sys.stderr.write(proc.stderr)
    print(f"header-check: {header} ok ({sum(len(f) for _, f in layouts().values())} offsets, "
          f"{len(STRUCTS)} sizes, {len(PROTOTYPES)} prototypes)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
